trigger:
  batch: true
  branches:
    include:
      - "*"
pr: none
pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'manage-courses-backend-poc'
  imageNameBgFindSync: 'manage-courses-bg-find-sync'
  imageNameBgGeoCode: 'manage-courses-bg-geocode'
  dockerOverride: 'docker-compose -f docker-compose.yml'

steps:
- script: |
    set -x
    GIT_SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c 1-7)
    docker_path=$(dockerHubUsername)/$(imageName)
    docker_bg_find_sync_path=$(dockerHubUsername)/$(imageNameBgFindSync)
    docker_bg_geocode_path=$(dockerHubUsername)/$(imageNameBgGeoCode)
    set +x # We confuse VSTS if we trace these commands
    echo "##vso[build.updatebuildnumber]$GIT_SHORT_SHA"
    echo "##vso[task.setvariable variable=docker_path;]$docker_path"
    echo "##vso[task.setvariable variable=docker_bg_find_sync_path;]$docker_bg_find_sync_path"
    echo "##vso[task.setvariable variable=docker_bg_geocode_path;]$docker_bg_geocode_path"
  displayName: 'Set version number'

- script: |
    set -x
    docker pull $(docker_path):latest || true
  displayName: "Pull latest docker image to cache"
- script: |
    set -x
    $DOCKER_OVERRIDE build
    $DOCKER_OVERRIDE up --no-build -d
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "./wait-for-command.sh -c 'nc -z db 5432' -s 0 -t 20"
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "bundle exec rails db:setup"
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "apk --no-cache add curl"
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "bundle exec rake cc:setup"
  displayName: 'Build & setup'
  env:
    DOCKER_OVERRIDE: $(dockerOverride)
    dockerHubUsername: $(dockerHubUsername)
    dockerHubImageName: $(imageName)
    CC_TEST_REPORTER_ID: $(ccReporterID)
- script: |
    set -x
    $DOCKER_OVERRIDE exec -T web /bin/sh -c 'bundle config --local disable_exec_load true'
    $DOCKER_OVERRIDE exec -T web /bin/sh -c 'bundle exec rake parallel:setup'
    $DOCKER_OVERRIDE exec -T web /bin/sh -c 'bundle exec rake "parallel:spec[,, -O .azure_parallel]"'

  displayName: 'Execute tests'
  env:
    DOCKER_OVERRIDE: $(dockerOverride)
    dockerHubUsername: $(dockerHubUsername)
    dockerHubImageName: $(imageName)
    CC_TEST_REPORTER_ID: $(ccReporterID)
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'rspec-output/*.xml'
    failedTaskOnFailedTest: true
- script: |
    set -x
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "bundle exec rubocop app config db lib spec --format clang"
  displayName: 'Execute linters'
  env:
    DOCKER_OVERRIDE: $(dockerOverride)
    dockerHubUsername: $(dockerHubUsername)
    dockerHubImageName: $(imageName)
- script: |
    set -x
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "bundle exec rake cc:report"
  displayName: 'Execute Code Climate reporter'
  env:
    DOCKER_OVERRIDE: $(dockerOverride)
    dockerHubUsername: $(dockerHubUsername)
    dockerHubImageName: $(imageName)
    CC_TEST_REPORTER_ID: $(ccReporterID)
    AGENT_JOBSTATUS: $(Agent.JobStatus)
- script: |
    set -x
    $DOCKER_OVERRIDE exec -T web /bin/sh -c "bundle exec rake brakeman"
  displayName: 'Execute Brakeman static analysis'
  env:
    DOCKER_OVERRIDE: $(dockerOverride)
    dockerHubUsername: $(dockerHubUsername)
    dockerHubImageName: $(imageName)
    AGENT_JOBSTATUS: $(Agent.JobStatus)
- task: Docker@1
  displayName: Tag image with current build number $(Build.BuildNumber)
  inputs:
    command: Tag image
    imageName: "$(docker_path):latest"
    arguments: "$(docker_path):$(Build.BuildNumber)"
- task: Docker@1
  displayName: Docker Hub login
  inputs:
    command: "login"
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DfE Docker Hub
- task: Docker@1
  displayName: Push tagged image
  inputs:
    command: Push an image
    imageName: "$(docker_path):$(Build.BuildNumber)"
- task: Docker@1
  displayName: Push tagged image (latest) if master
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: Push an image
    imageName: "$(docker_path):latest"

- task: Docker@1
  displayName: Tag bg_find_sync image with current build number $(Build.BuildNumber)
  inputs:
    command: Tag image
    imageName: "$(docker_bg_find_sync_path):latest"
    arguments: "$(docker_bg_find_sync_path):$(Build.BuildNumber)"

- task: Docker@1
  displayName: Push tagged image
  inputs:
    command: Push an image
    imageName: "$(docker_bg_find_sync_path):$(Build.BuildNumber)"

- task: Docker@1
  displayName: Tag bg_geocode image with current build number $(Build.BuildNumber)
  inputs:
    command: Tag image
    imageName: "$(docker_bg_geocode_path):latest"
    arguments: "$(docker_bg_geocode_path):$(Build.BuildNumber)"

- task: Docker@1
  displayName: Push tagged image
  inputs:
    command: Push an image
    imageName: "$(docker_bg_geocode_path):$(Build.BuildNumber)"

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: |
     azure/**
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
