shared:
  - search_results
  - track_click
  - saved_course
  - removed_saved_course
  - candidate_applies
  - candidate_note_created
  - candidate_note_updated
  - candidate_note_deleted
  - candidate_note_undone
