---
shared:
  authentication:
    - subject_key
  candidate:
    - email_address
  user:
    - email
    - first_name
    - last_name
    - sign_in_user_id
  session:
    - ip_address
  providers_onboarding_form_request:
    - email_address
    - first_name
    - last_name
