authentication:
  secret: secret
mcbg:
  redis_password:
system_authentication_token: "Ge32"
log_level: debug
gcp_api_key: please_change_me
environment:
  label: "development"
  name: "development"

features:
  display_migration_signin: false
